# WEB SCRAPING

## Data Scientist

In [77]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [79]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('Data Scientist')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [81]:
df = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': []})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='sal-wrap ver-line').text if post.find('span', class_='sal-wrap ver-line') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df
        df = pd.concat([df, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-data-scien...,Data Scientist - Phd only,NDS Infoserv,12-15 Lacs PA,Mumbai,Just Now
1,https://www.naukri.com/job-listings-data-scien...,Data Scientist - All Genpact locations,Genpact,Not disclosed,"Hyderabad, Gurugram, Bengaluru",Just Now
2,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Repucom,Not disclosed,Bengaluru,1 Day Ago
3,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Flipkart,Not disclosed,Bengaluru,1 Day Ago
4,https://www.naukri.com/job-listings-data-scien...,Data Scientist - Optimization Expertise,Repucom,Not disclosed,Bengaluru,1 Day Ago
5,https://www.naukri.com/job-listings-principal-...,Principal Data Scientist/Senior Data Scientist...,Benovymed Healthcare,Not disclosed,"Noida, Gurugram",6 Days Ago
6,https://www.naukri.com/job-listings-data-scien...,Data Scientist / Data Analyst,Leading Client,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",6 Days Ago
7,https://www.naukri.com/job-listings-data-scien...,Data Scientist / Data Analyst - Contract,Leading Client,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",3 Days Ago
8,https://www.naukri.com/job-listings-data-scien...,Data Scientist,V2soft,10-20 Lacs PA,Remote,1 Day Ago
9,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Capgemini,Not disclosed,Noida,1 Day Ago
10,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Avantor,Not disclosed,"Pune, Coimbatore",1 Day Ago
11,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Michelin,Not disclosed,Pune,1 Day Ago
12,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Wolters Kluwer - Medknow Publications,Not disclosed,"Kalyani, Pune",1 Day Ago
13,https://www.naukri.com/job-listings-senior-mac...,Senior Machine Learning Data Scientist - Produ...,Bungie,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",6 Days Ago
14,https://www.naukri.com/job-listings-data-scien...,Data Scientist: Artificial Intelligence,IBM,Not disclosed,Bengaluru,2 Days Ago
15,https://www.naukri.com/job-listings-data-scien...,Data Scientist: Artificial Intelligence,IBM,Not disclosed,Bengaluru,2 Days Ago
16,https://www.naukri.com/job-listings-data-scien...,Data Scientist,IBM,Not disclosed,Bengaluru,3 Days Ago
17,https://www.naukri.com/job-listings-gpsg-data-...,GPSG-Data Scientist,IBM,Not disclosed,Bengaluru,2 Days Ago
18,https://www.naukri.com/job-listings-data-scien...,Data Scientist III,Walmart,Not disclosed,Bengaluru,3 Days Ago
19,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Williams Lea,Not disclosed,"Kochi, Chennai",1 Day Ago

In [83]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

df

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-data-scien...,Data Scientist - Phd only,NDS Infoserv,12-15 Lacs PA,Mumbai,Just Now
1,https://www.naukri.com/job-listings-data-scien...,Data Scientist - All Genpact locations,Genpact,Not disclosed,"Hyderabad, Gurugram, Bengaluru",Just Now
2,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Repucom,Not disclosed,Bengaluru,1 Day Ago
3,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Flipkart,Not disclosed,Bengaluru,1 Day Ago
4,https://www.naukri.com/job-listings-data-scien...,Data Scientist - Optimization Expertise,Repucom,Not disclosed,Bengaluru,1 Day Ago
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Orange Business Services,Not disclosed,Gurugram,4 Days Ago
1516,https://www.naukri.com/job-listings-data-scien...,Data Scientist,NCR Atleos,Not disclosed,Gurugram,Just Now
1517,https://www.naukri.com/job-listings-data-scien...,Data Scientist(INDIA ONLY),Futurepath Ai,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",5 Days Ago
1518,https://www.naukri.com/job-listings-data-scien...,Data Scientist(INDIA ONLY),Futurepath Ai,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",5 Days Ago
1519,https://www.naukri.com/job-listings-data-scien...,Data Scientist,Larko Tech,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",5 Days Ago

In [85]:
df.to_csv('data sci.csv', index=False)

## Web developer

In [65]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [67]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('Web Developer')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [71]:
df1 = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': []})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal').text #if post.find('span', class_='sal-wrap ver-line') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df1
        df1 = pd.concat([df1, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df1

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-web-develo...,Web Developer,Essvee Consultant,2.5-3.75 Lacs PA,Gurugram,1 Day Ago
1,https://www.naukri.com/job-listings-web-develo...,Web Developer,Rigelix Technologies,Not disclosed,Pune,6 Days Ago
2,https://www.naukri.com/job-listings-web-develo...,Web Developer,Ixia Solutions,Not disclosed,"Thane, Panvel, Navi Mumbai",10 Days Ago
3,https://www.naukri.com/job-listings-web-develo...,Web Developer,HCLTech,Not disclosed,Hybrid - Noida,Just Now
4,https://www.naukri.com/job-listings-web-develo...,Web Developer,International Youth Club,Not disclosed,New Delhi,7 Days Ago
5,https://www.naukri.com/job-listings-web-develo...,Web Developer,Inframantra,Not disclosed,Gurugram,8 Days Ago
6,https://www.naukri.com/job-listings-web-develo...,Web Developer,Accenture,Not disclosed,Mumbai,3 Days Ago
7,https://www.naukri.com/job-listings-web-develo...,Web Developer,Star Design Institute,Not disclosed,Hyderabad(Ameerpet),6 Days Ago
8,https://www.naukri.com/job-listings-web-develo...,Web Developer,FX Master,4.75-6 Lacs PA,Hybrid - Hyderabad,1 Day Ago
9,https://www.naukri.com/job-listings-web-develo...,Web Developer,Cialfo,Not disclosed,New Delhi,1 Day Ago
10,https://www.naukri.com/job-listings-web-develo...,Web Developer,Accenture,Not disclosed,Gurugram,3 Days Ago
11,https://www.naukri.com/job-listings-web-develo...,Web Developer,Accenture,Not disclosed,Gurugram,3 Days Ago
12,https://www.naukri.com/job-listings-web-develo...,Web Developer,Accenture,Not disclosed,Pune,6 Days Ago
13,https://www.naukri.com/job-listings-web-develo...,Web Developer,ONS Tech,Not disclosed,Zirakpur,1 Day Ago
14,https://www.naukri.com/job-listings-web-develo...,Web Developers,Dgvalley Technologies,Not disclosed,Bhopal,1 Day Ago
15,https://www.naukri.com/job-listings-web-develo...,Web Developer,Brickwork India,Not disclosed,Bengaluru,2 Days Ago
16,https://www.naukri.com/job-listings-web-develo...,Web Developer,U4IC Media,2.25-3.5 Lacs PA,Noida,1 Day Ago
17,https://www.naukri.com/job-listings-web-develo...,Web Developer,Accenture,Not disclosed,Mumbai,8 Days Ago
18,https://www.naukri.com/job-listings-web-develo...,Web Developer,United Nations Development Programme (UNDP),Not disclosed,New Delhi,3 Days Ago
19,https://www.naukri.com/job-listings-web-develo...,Web Developer,ISS Corporate Solutions,Not disclosed,Mumbai,1 Day Ago

In [73]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

In [74]:
df1

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-web-develo...,Web Developer,Essvee Consultant,2.5-3.75 Lacs PA,Gurugram,1 Day Ago
1,https://www.naukri.com/job-listings-web-develo...,Web Developer,Rigelix Technologies,Not disclosed,Pune,6 Days Ago
2,https://www.naukri.com/job-listings-web-develo...,Web Developer,Ixia Solutions,Not disclosed,"Thane, Panvel, Navi Mumbai",10 Days Ago
3,https://www.naukri.com/job-listings-web-develo...,Web Developer,HCLTech,Not disclosed,Hybrid - Noida,Just Now
4,https://www.naukri.com/job-listings-web-develo...,Web Developer,International Youth Club,Not disclosed,New Delhi,7 Days Ago
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-web-develo...,Web Developer,Teledyne Technologies,Not disclosed,Pune,5 Days Ago
1516,https://www.naukri.com/job-listings-web-develo...,Web Developer,Trigent Software,1-3.5 Lacs PA,Mumbai,3 Days Ago
1517,https://www.naukri.com/job-listings-web-develo...,Web Developer,Laremibiztv,Not disclosed,Remote,2 Days Ago
1518,https://www.naukri.com/job-listings-web-develo...,Web Developer,Techdost Services,Not disclosed,Meerut,3 Days Ago
1519,https://www.naukri.com/job-listings-web-develo...,Web Developer,Teledyne Technologies,Not disclosed,Pune,7 Days Ago

In [91]:
df1.to_csv('web developer.csv', index=False)

## Data Analyst

In [95]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [97]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('Data Analyst')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [114]:
df2 = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': []})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal').text if post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df2
        df2 = pd.concat([df2, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df2

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-data-analy...,"Data Analyst (Role based in Riyadh, Saudi Arab...",Harrier X IT Consulting and Services,Not Disclosed,Saudi Arabia,4 Days Ago
1,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Telecmi,Not disclosed,Viluppuram,6 Days Ago
2,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Clarivate,Not disclosed,Bengaluru,1 Day Ago
3,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Hiring for Banks,10-17 Lacs PA,Mumbai (All Areas),1 Day Ago
4,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Druva Inc.,Not disclosed,Pune,Just Now
5,https://www.naukri.com/job-listings-data-scien...,Data Scientist / Data Analyst - Contract,Leading Client,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",3 Days Ago
6,https://www.naukri.com/job-listings-data-scien...,Data Scientist / Data Analyst,Leading Client,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",6 Days Ago
7,https://www.naukri.com/job-listings-data-analy...,Data Analyst - Looker,Tetrahed Inc,Not disclosed,"Noida, Hyderabad, Pune",8 Days Ago
8,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Anarock Property Consultants,Not disclosed,Mumbai (All Areas),10 Days Ago
9,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Jio,Not disclosed,"Thane, Navi Mumbai, Mumbai (All Areas)",2 Days Ago
10,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Cafyo Management Solution,1.5-3 Lacs PA,"Bhilai, Bilaspur",9 Days Ago
11,https://www.naukri.com/job-listings-data-analy...,Data Analyst,TechnoIdentity,Not disclosed,Remote,7 Days Ago
12,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Different Hair,3.5-6 Lacs PA,"Sriperumbudur, Chennai",10 Days Ago
13,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Saksoft,Not disclosed,Mumbai,Just Now
14,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Motivity Labs,Not disclosed,Hybrid - Bengaluru,Just Now
15,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Axa Xl,Not disclosed,Bengaluru,1 Day Ago
16,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Blueoptima,Unpaid,Bengaluru,Starts in 1-3 months
17,https://www.naukri.com/job-listings-category-d...,Category Data Analyst,Hfele,Not disclosed,Mumbai,1 Day Ago
18,https://www.naukri.com/job-listings-data-analy...,Data Analyst,SLK Software,Not disclosed,Bengaluru,3 Days Ago
19,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Axa Technology Services,Not disclosed,Bengaluru,3 Days Ago

In [116]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

df2

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-data-analy...,"Data Analyst (Role based in Riyadh, Saudi Arab...",Harrier X IT Consulting and Services,Not Disclosed,Saudi Arabia,4 Days Ago
1,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Telecmi,Not disclosed,Viluppuram,6 Days Ago
2,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Clarivate,Not disclosed,Bengaluru,1 Day Ago
3,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Hiring for Banks,10-17 Lacs PA,Mumbai (All Areas),1 Day Ago
4,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Druva Inc.,Not disclosed,Pune,Just Now
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Axa Xl,Not disclosed,Bengaluru,1 Day Ago
1516,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Blueoptima,Unpaid,Bengaluru,Starts in 1-3 months
1517,https://www.naukri.com/job-listings-category-d...,Category Data Analyst,Hfele,Not disclosed,Mumbai,1 Day Ago
1518,https://www.naukri.com/job-listings-data-analy...,Data Analyst,SLK Software,Not disclosed,Bengaluru,3 Days Ago
1519,https://www.naukri.com/job-listings-data-analy...,Data Analyst,Axa Technology Services,Not disclosed,Bengaluru,3 Days Ago

In [118]:
df2.to_csv('data analyst.csv', index=False)

## Cloud Engineer

In [121]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [123]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('Cloud Engineer')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [125]:
df3 = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': []})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal').text if post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df3
        df3 = pd.concat([df3, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df3

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Bengaluru,Just Now
1,https://www.naukri.com/job-listings-gcp-cloud-...,GCP Cloud Engineer - R-19409,Rackspace Technology,Not disclosed,Remote,6 Days Ago
2,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Pune,Just Now
3,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Linkageit,Not disclosed,Bengaluru,6 Days Ago
4,https://www.naukri.com/job-listings-gcp-cloud-...,GCP Cloud Engineer,M3bi,15-25 Lacs PA,"Gurugram, Bengaluru",11 Days Ago
5,https://www.naukri.com/job-listings-cloud-engi...,"Cloud Engineer, Advanced",Antuit,Not disclosed,Bengaluru,4 Days Ago
6,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Bengaluru,3 Days Ago
7,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Bengaluru,7 Days Ago
8,https://www.naukri.com/job-listings-gcp-cloud-...,GCP Cloud Engineer,Global Pharma Tek,Not disclosed,Hyderabad,13 Days Ago
9,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Capgemini,Not disclosed,Bengaluru,2 Days Ago
10,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Indore,3 Days Ago
11,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Indore,7 Days Ago
12,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer - C,Capgemini,Not disclosed,Bengaluru,3 Days Ago
13,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Hyderabad,7 Days Ago
14,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Travelex,Not disclosed,Mumbai,1 Day Ago
15,https://www.naukri.com/job-listings-oracle-vmw...,ORACLE/VMware CLOUD ENGINEER,Allime Tech Solutions,Not disclosed,Chennai,Just Now
16,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Hari Har Consultancy Llp,8-11 Lacs PA,"Hybrid - Hyderabad, Bengaluru, Mumbai (All Areas)",5 Days Ago
17,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Bengaluru,8 Days Ago
18,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Keyloop,Not disclosed,Hyderabad,9 Days Ago
19,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Thryve Digital,Not disclosed,"Hyderabad, Chennai",7 Days Ago

In [127]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

df3

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Bengaluru,Just Now
1,https://www.naukri.com/job-listings-gcp-cloud-...,GCP Cloud Engineer - R-19409,Rackspace Technology,Not disclosed,Remote,6 Days Ago
2,https://www.naukri.com/job-listings-cloud-nati...,Cloud Native Engineer,Accenture,Not disclosed,Pune,Just Now
3,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Linkageit,Not disclosed,Bengaluru,6 Days Ago
4,https://www.naukri.com/job-listings-gcp-cloud-...,GCP Cloud Engineer,M3bi,15-25 Lacs PA,"Gurugram, Bengaluru",11 Days Ago
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-cloud-prac...,Cloud Practice Engineer V,Rackspace Technology,Not disclosed,Remote,3 Days Ago
1516,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer,Magna International,Not disclosed,Bengaluru,8 Days Ago
1517,https://www.naukri.com/job-listings-cloud-engi...,Cloud Engineer I GCP,Concentrix,10-18 Lacs PA,"New Delhi, Gurugram",30+ Days Ago
1518,https://www.naukri.com/job-listings-technical-...,Technical Leader Cloud Engineer,Webex Communications India (p) Ltd.,Not disclosed,Bengaluru,7 Days Ago
1519,https://www.naukri.com/job-listings-onsite-dri...,Onsite Drive - Cloud Engineer,TerraPay,Not disclosed,Bengaluru,14 Days Ago

In [131]:
df3.to_csv('cloud engineer.csv', index=False)

## Cyber Security Analyst/Engineer

In [134]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [136]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('Cyber Security')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [138]:
df4 = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': []})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal').text if post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df4
        df4 = pd.concat([df4, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df4

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Analyst,TAC Security,Not disclosed,Mumbai(Lower Parel),1 Day Ago
1,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Analyst,Leading Client,Not disclosed,Mumbai,1 Day Ago
2,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Engineer-Automotive(5+ Yrs)\n,Tata Elxsi,Not disclosed,Hybrid - Bengaluru,Just Now
3,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Engineer,Deloitte,6-11 Lacs PA,"Hyderabad, Mumbai (All Areas)",1 Day Ago
4,https://www.naukri.com/job-listings-cyber-secu...,Cyber-Security Risk Analyst,Vensure Employer Solutions,Not disclosed,Hybrid - Noida,1 Day Ago
5,https://www.naukri.com/job-listings-director-c...,Director - Cyber Security,Wipro,Not disclosed,"Pune, Chennai, Bengaluru",1 Day Ago
6,https://www.naukri.com/job-listings-sr-associa...,"Sr Associate, Cyber Security IT RiskM",Northern Trust,Not disclosed,Bengaluru,8 Days Ago
7,https://www.naukri.com/job-listings-analyst-in...,Analyst Information & Cyber Security,Iris Solutions,Not disclosed,Noida,1 Day Ago
8,https://www.naukri.com/job-listings-cyber-secu...,Cyber-Security Engineer / Architect,IBM,Not disclosed,Bengaluru,2 Days Ago
9,https://www.naukri.com/job-listings-manager-cy...,Manager - Cyber Security,Mphasis,Not disclosed,Bengaluru,3 Days Ago
10,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Engineer,Russell Investments,Not disclosed,Mumbai,5 Days Ago
11,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Specialist,Avalon Technologies,Not disclosed,Chennai,13 Days Ago
12,https://www.naukri.com/job-listings-presales-e...,Presales Engineer - Cyber Security,TAC Security,Not disclosed,Mumbai,1 Day Ago
13,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Analyst - Risk & PAM,Societe Generale Global Solution Centre,Not disclosed,Bengaluru,7 Days Ago
14,https://www.naukri.com/job-listings-program-ma...,Program Manage (Information/Cyber Security Exp...,National Institute for Smart Government (NISG),30-45 Lacs PA,"New Delhi, Delhi / NCR",3 Days Ago
15,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Analyst III,Simplicity First,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",8 Days Ago
16,https://www.naukri.com/job-listings-lead-cyber...,Lead Cyber Security Analyst - Flow Certificati...,Global Pharma Tek,Not disclosed,Bengaluru,13 Days Ago
17,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Lead Analyst-Imperva,Global Pharma Tek,Not disclosed,Bengaluru,13 Days Ago
18,https://www.naukri.com/job-listings-cyber-secu...,CYBER Security Specialist - Mumbai,Executive Ship Management (ESM),12-15 Lacs PA,"Mumbai(Govandi East), Navi Mumbai",Just Now
19,https://www.naukri.com/job-listings-senior-cyb...,Senior Cyber Security Analyst,Tectona,3.5-6 Lacs PA,Ahmedabad,6 Days Ago

In [140]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

df4

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Analyst,TAC Security,Not disclosed,Mumbai(Lower Parel),1 Day Ago
1,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Analyst,Leading Client,Not disclosed,Mumbai,1 Day Ago
2,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Engineer-Automotive(5+ Yrs)\n,Tata Elxsi,Not disclosed,Hybrid - Bengaluru,Just Now
3,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Engineer,Deloitte,6-11 Lacs PA,"Hyderabad, Mumbai (All Areas)",1 Day Ago
4,https://www.naukri.com/job-listings-cyber-secu...,Cyber-Security Risk Analyst,Vensure Employer Solutions,Not disclosed,Hybrid - Noida,1 Day Ago
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-hiring-ass...,Hiring Associate Cyber Security & IT Governanc...,Million Minds Management Services,10-12 Lacs PA,Bengaluru(100 Feet Road),2 Days Ago
1516,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security professional,Infosys,Not disclosed,Bengaluru,3 Days Ago
1517,https://www.naukri.com/job-listings-manager-cy...,Manager - Cyber Security,Mphasis,Not disclosed,Bengaluru,3 Days Ago
1518,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security - Marketing Executive,Infosys,Not disclosed,"Hybrid - Pune, Bengaluru",7 Days Ago
1519,https://www.naukri.com/job-listings-cyber-secu...,Cyber Security Intern,R C W M A S Global,Unpaid,Remote,Starts in 1-3 months

In [146]:
df4.to_csv('cyber.csv', index=False)

## UI/UX Designer

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [8]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64 (1)\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('UI/UX Designer')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [14]:
df5 = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': [],'Experience':[],'Skills':[], 'Day Posted':[]})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='sal-wrap ver-line').text if post.find('span', class_='sal-wrap ver-line') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        experience=post.find('span',class_='ni-job-tuple-icon ni-job-tuple-icon-srp-experience exp').text


# Extract and clean skills
        raw_skills = post.find('ul', class_='tags-gt ').text

# # Use a regex to insert a comma before each capital letter and clean the string
#         cleaned_skills = re.sub(r'(?<=[a-z])(?=[A-Z])', ', ', raw_skills).strip()

# # Remove extra spaces or trailing commas
#         cleaned_skills = ", ".join([skill.strip() for skill in cleaned_skills.split(',')])
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Experience':[experience],
            'Skills':[raw_skills],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df
        df = pd.concat([df, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df5

AttributeError: 'NoneType' object has no attribute 'text'

In [16]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

df5

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer,Ebizon Net Info,Not disclosed,Dehradun,1 Day Ago
1,https://www.naukri.com/job-listings-ux-and-ui-...,Ux And Ui Designer,Elasticrun,Not disclosed,Pune,Few Hours Ago
2,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer - Figma/Sketch - Internship,Leading Client,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",5 Days Ago
3,https://www.naukri.com/job-listings-ui-ux-desi...,ui ux designer,Star Design Institute,Not disclosed,Hyderabad,9 Days Ago
4,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer,Epsilon Money Mart,6-7 Lacs PA,Mumbai Suburban,4 Days Ago
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-ui-ux-desi...,UI UX Designer,the Sleep Company,20-25 Lacs PA,Mumbai(Oshiwara),5 Days Ago
1516,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer,Social Donut,Not disclosed,Mumbai,10 Days Ago
1517,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer,Infosys,Not disclosed,"Noida, Pune, Bengaluru",Today
1518,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer,Salesforce,Unpaid,"Hyderabad, Bengaluru",Starts in 1-3 months
1519,https://www.naukri.com/job-listings-ui-ux-desi...,UI/UX Designer,Capgemini,Not disclosed,Gurugram,1 Day Ago

In [24]:
df5.to_csv('UI.csv', index=False)

# Blockchain Engineer

In [5]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import pandas as pd 
import time
import requests

In [9]:
# Define the path to ChromeDriver using a raw string
driver_path = r"D:\My Data\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"

# Initialize the Service object
service = Service(executable_path=driver_path)

# Start the WebDriver
driver = webdriver.Chrome(service=service)

# Open the Naukri website
driver.get('https://www.naukri.com/')

input_search = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[1]/div/div/div[1]/div[1]/div/input')

input_search.send_keys('Blockchain Engineer')

button = driver.find_element(By.XPATH, '//*[@id="root"]/div[7]/div/div/div[6]').click()

In [11]:
df6 = pd.DataFrame({'Link': [], 'Job Title': [], 'Company': [], 'Salary': [], 'Location': []})
def scrape_job_data():
    soup = BeautifulSoup(driver.page_source, 'lxml')
'    posting = soup.find_all('div', class_='srp-jobtuple-wrapper')
    
    for post in posting:
        link = post.find('a', class_='title').get('href')
        name = post.find('a', class_='title').text
        company = post.find('a', class_='comp-name').text
        salary = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal').text if post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-rupee sal') else 'Not Disclosed'
        location = post.find('span', class_='ni-job-tuple-icon ni-job-tuple-icon-srp-location loc').text
        Day_posted = post.find('span', class_ ='job-post-day').text
        
        new_row = pd.DataFrame({
            'Link': [link],
            'Job Title': [name],
            'Company': [company],
            'Salary': [salary],
            'Location': [location],
            'Day Posted': [Day_posted]
        })
        # Append the new row to the DataFrame
        global df6
        df6 = pd.concat([df6, new_row], ignore_index=True)

# Scrape data for the first page
scrape_job_data()

# Print the collected data
df6

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-blockchain...,"Blockchain Engineer, R3 Corda",Xalts,Not disclosed,Bengaluru,22 Days Ago
1,https://www.naukri.com/job-listings-blockchain...,Blockchain Engineer,M/s Wifi Dabba India,Not disclosed,Bengaluru,30+ Days Ago
2,https://www.naukri.com/job-listings-blockchain...,Blockchain Engineer,Coindcx,Not disclosed,Bengaluru,30+ Days Ago
3,https://www.naukri.com/job-listings-blockchain...,Blockchain Engineer,Jupitice Justice Technologies,Not disclosed,Chandigarh,30+ Days Ago
4,https://www.naukri.com/job-listings-ethereum-b...,Ethereum Blockchain Engineer,Zeeve,Not disclosed,Dehradun,30+ Days Ago
5,https://www.naukri.com/job-listings-jr-blockch...,Jr. Blockchain (Web3) Engineer,Cloud Counselage,Not disclosed,Mumbai,30+ Days Ago
6,https://www.naukri.com/job-listings-senior-blo...,Senior Blockchain Engineer,Cryptape,Not disclosed,Remote,30+ Days Ago
7,https://www.naukri.com/job-listings-senior-blo...,Senior Blockchain Engineer,Trans Fi,Not disclosed,Remote,30+ Days Ago
8,https://www.naukri.com/job-listings-staff-bloc...,Staff Blockchain Engineer,Ex Populus,Not disclosed,Remote,30+ Days Ago
9,https://www.naukri.com/job-listings-mcad-engin...,MCAD Engineer,Emerson Network Power,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",1 Day Ago
10,https://www.naukri.com/job-listings-blockchain...,"Blockchain Engineer, EVM",Xalts,Not disclosed,Bengaluru,23 Days Ago
11,https://www.naukri.com/job-listings-senior-blo...,Senior Blockchain Engineer,Coindcx,Not disclosed,Bengaluru,30+ Days Ago
12,https://www.naukri.com/job-listings-engineer-e...,Engineer,ECE Elevators,Not disclosed,"Mumbai, Jaipur",1 Day Ago
13,https://www.naukri.com/job-listings-blockchain...,Blockchain Developer,Shashwath Solution,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",1 Day Ago
14,https://www.naukri.com/job-listings-eloqua-eng...,Eloqua Engineers,Buxton Consulting (india),Not disclosed,"Hybrid - Hyderabad, Bengaluru, Mumbai (All Areas)",1 Day Ago
15,https://www.naukri.com/job-listings-dc-enginee...,DC Engineer,Hexaware Technologies,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",1 Day Ago
16,https://www.naukri.com/job-listings-wordpress-...,WordPress Engineer(6-12 year),Glan Management Consultancy,Not disclosed,Mumbai,1 Day Ago
17,https://www.naukri.com/job-listings-principal-...,Principal Software Engineer - Blockchain,Shardeum Foundation,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",10 Days Ago
18,https://www.naukri.com/job-listings-kiln-engin...,Kiln Engineer,Proficient Kiln Services,2-3.25 Lacs PA,Navi Mumbai,4 Days Ago
19,https://www.naukri.com/job-listings-microsoft-...,Microsoft Full Stack Engineer - Professional,Hexaware Technologies,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",2 Days Ago

In [13]:
page_count = 1
while page_count<=75:
    try:
        # Wait until the "Next" button is clickable
        next_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//*[@id="lastCompMark"]/div[2]/a[2]'))
        )

        # If the button is found and clickable, click it
        next_button.click()

        # Wait for the page to load after clicking
        time.sleep(3)

        # Scrape job data from the next page
        scrape_job_data()
        page_count +=1 

    except Exception as e:
        print(f"No more pages to scrape: {e}")
        break

df6

,Link,Job Title,Company,Salary,Location,Day Posted
0,https://www.naukri.com/job-listings-blockchain...,"Blockchain Engineer, R3 Corda",Xalts,Not disclosed,Bengaluru,22 Days Ago
1,https://www.naukri.com/job-listings-blockchain...,Blockchain Engineer,M/s Wifi Dabba India,Not disclosed,Bengaluru,30+ Days Ago
2,https://www.naukri.com/job-listings-blockchain...,Blockchain Engineer,Coindcx,Not disclosed,Bengaluru,30+ Days Ago
3,https://www.naukri.com/job-listings-blockchain...,Blockchain Engineer,Jupitice Justice Technologies,Not disclosed,Chandigarh,30+ Days Ago
4,https://www.naukri.com/job-listings-ethereum-b...,Ethereum Blockchain Engineer,Zeeve,Not disclosed,Dehradun,30+ Days Ago
...,...,...,...,...,...,...
1515,https://www.naukri.com/job-listings-engineer-j...,Engineer,Jacobs,Not disclosed,Navi Mumbai,14 Days Ago
1516,https://www.naukri.com/job-listings-agl-engine...,AGL Engineer,Jacobs,Not disclosed,Mumbai,14 Days Ago
1517,https://www.naukri.com/job-listings-trainee-en...,Trainee Engineer/ Technician,Planttech Industrial Services Limited,2-2.5 Lacs PA,"Panipat, Visakhapatnam, Mumbai (All Areas)",14 Days Ago
1518,https://www.naukri.com/job-listings-teradata-e...,Teradata Engineer,Smart Wealth,Not disclosed,"Mumbai, Delhi / NCR, Bengaluru",18 Days Ago
1519,https://www.naukri.com/job-listings-engineer-w...,Engineer,W Goa,Not disclosed,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C...",18 Days Ago

In [15]:
df6.to_csv('blockchain engineer.csv', index=False)